version: '2'
services:
  kafka:
    image: flozano/kafka:0.9.0.0
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: ${DOCKER_IP}
  elasticsearch:
    image: elasticsearch:2.3.5
    ports:
      - "9200:9200"
      - "9300:9300"
